# Generated by Django 3.0.6 on 2020-05-29 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200529_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikel',
            options={'default_permissions': ('add', 'change', 'delete'), 'permissions': (('publish_artikel', 'Can publish artikel'),)},
        ),
    ]
