# Generated by Django 3.0.6 on 2020-05-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='content',
            field=models.CharField(default='programming', max_length=100),
            preserve_default=False,
        ),
    ]
