# Generated by Django 3.0.6 on 2020-05-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='author', max_length=100),
            preserve_default=False,
        ),
    ]
