# Generated by Django 3.0.6 on 2020-05-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('jurnal', 'jurnal'), ('blog', 'blog'), ('berita', 'berita')], default='blog', max_length=100),
        ),
    ]
