# Generated by Django 3.0.6 on 2020-05-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('jurnal', 'jurnal'), ('berita', 'berita'), ('gosip', 'gosip')], default='jurnal', max_length=100)),
            ],
        ),
    ]
